### ISSUE TITLE
K8s: S3 Authentication (Access/Secret-Keys) not available

### ISSUE THREAD

**Issue by matthiasritter** [awslabs/aws-servicebroker#111]
**Describe the bug**
We want to provision S3-Buckets in our K8s-Cluster. If we create an S3-Binding, there is no Access and Secret Key.

**To Reproduce**
Logs from the creation of the Binding:
```
aws-servicebroker-fb4d5c7c-d7jw7 awssb I0430 12:55:15.354264       1 awsbroker.go:208] Client OSB API Version: "2.13"
aws-servicebroker-fb4d5c7c-d7jw7 awssb I0430 12:55:15.354324       1 apisurface.go:290] Received BindRequest for instanceID "6643085b-6b45-11e9-8c78-42658f073859", bindingID "32b78d9b-6b47-11e9-8c78-42658f073859"
aws-servicebroker-fb4d5c7c-d7jw7 awssb I0430 12:55:15.354331       1 api.go:279] request={BindingID:32b78d9b-6b47-11e9-8c78-42658f073859 InstanceID:6643085b-6b45-11e9-8c78-42658f073859 AcceptsIncomplete:false ServiceID:dcadf63a-467e-55bd-8f68-ba76bc286f88 PlanID:e4d77d27-3acb-572d-bee8-590f9b94698e AppGUID:<nil> BindResource:0xc000478200 Parameters:map[] Context:map[clusterid:1c0d8d17-5b68-11e9-b5f3-7203243ef715 namespace:lxos-infra platform:kubernetes] OriginatingIdentity:0xc0005541c0}
aws-servicebroker-fb4d5c7c-d7jw7 awssb I0430 12:55:15.471159       1 util.go:195] Did not find 'aws_access_key' and 'aws_secret_key' in params, using default chain.
aws-servicebroker-fb4d5c7c-d7jw7 awssb I0430 12:55:15.471179       1 aws_sdk.go:71] Parameter 'target_role_name' not set. Not assuming role.
```

**Expected behavior**
We expect that an IAM-Role is created for the bucket as described in the cloudformation-tempalte:
https://github.com/awslabs/aws-servicebroker/blob/master/templates/s3/template.yaml#L21-L55
This credentials should be (as mentioned in your documentation) available in the k8s-secret
https://aws.amazon.com/de/blogs/opensource/kubernetes-service-catalog-aws-service-broker-on-eks/

**Environment (please complete the following information):**
 - Application Platform: Kubernetes
 - Application Platform Version: 1.13.4
 - Broker Version: STABLE

**Comment by TheKangaroo** [comment]
Actually, I see the same behavior. If I recall correctly it used to push an access/secret key to the kubernetes secret when I build a POC in our k8s cluster some months ago. 
But as I redeployed the servicebroker lately I had the same issue.
I'm also somewhat confused since the docs point out, that the service binding should create a resource with just BUCKET_NAME, BUCKET_ARN, and BUCKET_LOGGING_NAME (https://github.com/awslabs/aws-servicebroker/blob/master/templates/s3/README.md#bind-credentials) but the blog post linked by @matthiasritter shows additional keys S3_AWS_ACCESS_KEY_ID and S3_AWS_SECRET_ACCESS_KEY, which is what I expected.
  
Any ideas on what I/we are missing? 🤔

**Comment by TheKangaroo** [comment]
Thank you @jaymccon for fixing this 🎉
