### ISSUE TITLE
elasticsearch clusterserviceplan fails to create

### ISSUE THREAD

**Issue by k** [awslabs/aws-servicebroker#135]
**Describe the bug**
When creating elasticsearch prod clusterserviceplan it fails to create subnet 3

**To Reproduce**
Create a serviceinstance of externalName elasticsearch with production plan

**Expected behavior**
The CloudFormation template would not fail

**Environment (please complete the following information):**
 - Application Platform: Kubernetes EKS
 - Application Platform Version: v1.12.7
 - Broker Version 0.1.0

**Additional context**
elasticsearch dev plan works properly

**Comment by jaymccon** [comment]
Are you able to provide the cloudformation failure message?

**Comment by jaymccon** [comment]
cc @ndrest-amzn

**Comment by ndrest-amzn** [comment]
Recreated an error when using 3 AZs. Cloudformation does not yet support a 3AZ Elasticsearch deployment due to a limitation with the ZoneAwareness property, this is a known issue within Cloudformation. Only 1 or 2AZ is currently supported when provisioned via Cloudformation.

I will resolve this limitation in the template and send a PR. The change will ensure only a 1 or 2 AZ deployment is permitted.

**Comment by ndrest-amzn** [comment]
https://github.com/awslabs/aws-servicebroker/pull/130
