### ISSUE TITLE
remove aws_access_key and aws_secret_key from templates and nonCfnParams

### ISSUE THREAD

**Issue by jaymccon** [awslabs/aws-servicebroker#41]
Currently we're exposing 2 mechanisms for specifying an IAM identity to use for provisioning/binding. The option of providing hard-coded credentials to use was originally the only option for this. Now with the cross-account assume role option, I don't see any value in the hard-coded credentials. 

Additionally, having both available introduces confusion in platforms that present a ui, as the options are mutually exclusive and there is no guidance on precedence should a user provide both.

@vsomayaji are there any use-cases you can think of that would warrant keeping these ?

**Comment by vsomayaji** [comment]
@jaymccon am I understanding this correctly: the service broker will continue to support running using an `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` instead of an instance profile, but it will no longer support using those credentials for provisioning/binding; instead, it will always assume `target_role_name` (optionally in `target_account_id`) for those operations.

If so, I like it. It will eliminate some confusion and it means we won't be storing long-lived credentials in the metadata table. Unless someone else objects, I say do it.

**Comment by jaymccon** [comment]
implemented in beta.2
